### ISSUE TITLE
Leave out setPixels in Step 5 - stylizeImage()

### ISSUE THREAD

**Issue by fabianeichinger** [googlecodelabs/tensorflow-style-transfer-android#1]
The code block for what goes into `stylizeImage(Bitmap)` made me think I'd have to add `bitmap.setPixels(intValues, …)` myself. It took me a while to realize that conversion from float to int and setting of pixels is already in the fetched code.

**Comment by markmcd** [comment]
Thanks for the report - I've updated the codelab instructions to make this clearer. Let me know if you think it's not.
