### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by FirdousNath** [googlecodelabs/tensorflow-style-transfer-android#10]
I followed every step as it is bu could not find filtration , camera simply  shows same image

**Comment by markmcd** [comment]
Without any code, I can't really help a great deal. I've just run through myself and it all seems to be working fine for me... Something that may help you would be to check out the [`codelab-finish`](/googlecodelabs/tensorflow-style-transfer-android/tree/codelab-finish) branch, and see if it works - if so, it may indicate that something was missed or copied incorrectly from the codelab.

Another thing to try would be to 'diff' your code against the solution, e.g. by running `git diff codelab-finish`, which will show any discrepancies between the expected solution and your own.
