### ISSUE TITLE
stylizeActivity setPixels does not have the correct for loop

### ISSUE THREAD

**Issue by claywilkinson** [googlecodelabs/tensorflow-style-transfer-android#2]
This code for setPixels should be in  a for loop and have more parameters?

Thanks!

 inferenceInterface.fetch(OUTPUT_NODE, floatValues);

 // ... provided code to convert float array to array of RGB ints ...
 bitmap.setPixels(intValues, ...);
}

**Comment by markmcd** [comment]
Sorry - the instructions about which code to copy & paste was not clear - I've updated the lab to make it clearer. HTH.
