### ISSUE TITLE
Running 3.0 Canary 1

### ISSUE THREAD

**Issue by anyagk** [googlecodelabs/tensorflow-style-transfer-android#3]
Error:Execution failed for task ':prepareOrgTensorflowTensorflowAndroid120PreviewLibrary'.
> Could not initialize class com.android.ide.common.util.ReadWriteProcessLock

**Comment by markmcd** [comment]
Thanks for the report - I've not been able to reproduce this one so I'm going to say it was unique to the machine we used at I/O.

If anyone else runs into this, there is a newer version of the TF inference library that you could try - replace `org.tensorflow:tensorflow-android:1.2.0-preview` with `org.tensorflow:tensorflow-android:1.2.0-rc0` in build.gradle.
