### ISSUE TITLE
NUM_STYLES already defined

### ISSUE THREAD

**Issue by JesseScott** [googlecodelabs/tensorflow-style-transfer-android#5]
NUM_STYLES is included in the variables at https://codelabs.developers.google.com/codelabs/tensorflow-style-transfer-android/index.html?index=..%2F..%2Findex#4 (Section **Add the inference code**) that wea re supposed to add to the Activity.

But it is already defined in StylizeActivity at https://github.com/googlecodelabs/tensorflow-style-transfer-android/blob/codelab-finish/android/src/org/tensorflow/demo/StylizeActivity.java#L74

It seems to have several uses already, so rather than doing a Pull Request and removing it from the code, it would be best to drop it from the CodeLab text

**Comment by markmcd** [comment]
Great point, thanks for the submission. I've added some comments to the codelab, does that look OK to you? [Codelab step 5](https://codelabs.developers.google.com/codelabs/tensorflow-style-transfer-android/index.html?index=..%2F..%2Findex#4)

(closing, will reopen if there's further suggestions)

**Comment by JesseScott** [comment]
Perfect!
