### ISSUE TITLE
 manager.openCamera(cameraId, stateCallback, backgroundHandler);

### ISSUE THREAD

**Issue by Saritaarya** [googlecodelabs/tensorflow-style-transfer-android#6]
this method showing error 
this app's filter is not running but simple camera is work

**Comment by markmcd** [comment]
There's no enough information here to troubleshoot unfortunately. Please include the error, an as much information about the environment as possible (e.g. are you using the code verbatim from this repository, if so, which branch)? what kind of phone are you using? what version of android are you running?)

It might be worth pointing out that the default branch (master) is the start of the codelab, where you will see the camera preview but you will not yet see the stylized image. You'll notice that step 5 of the codelab is where you add the code to stylize using TensorFlow: https://codelabs.developers.google.com/codelabs/tensorflow-style-transfer-android/#4

**Comment by shakyaninja** [comment]
This is error message:
`Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException`
