### ISSUE TITLE
app has stopped

### ISSUE THREAD

**Issue by junaidwahid** [googlecodelabs/tensorflow-style-transfer-android#7]
After following all the instructions, when i installed the app in my mobile then when i open this app it stops by showing error that your app has been stopped. Please help me how to resolve this issue?

**Comment by markmcd** [comment]
There's not enough info here to help troubleshoot your problem. Can you please include the relevant logcat output when the app crashes?

As an extra aid, you can try downloading the finished APK from the [nightly build page](https://ci.tensorflow.org/view/Nightly/job/nightly-android/) (Click 'Last Successful Artifacts' -> View/out/native/tensorflow_demo.apk) and see if that runs on your device.
