### ISSUE TITLE
Link not working in 5th step of Codelab tensorflow-style-transfer-android

### ISSUE THREAD

**Issue by naushy** [googlecodelabs/tensorflow-style-transfer-android#8]
JCenter Link for adding TensorFlow Android Inference Library and Java API here is broken 
https://bintray.com/google/tensorflow/tensorflow-android

**Comment by divzhere** [comment]
Can't open https://bintray.com/google/tensorflow/tensorflow-android

**Comment by markmcd** [comment]
Thanks for the report - no idea where it's gone, but there are dead links on the main [tensorflow](https://github.com/tensorflow/tensorflow) repo too. I'll email the team & see what happened.

**Comment by markmcd** [comment]
Looks like it's moved over here: https://bintray.com/google/tensorflow/tensorflow#files/org%2Ftensorflow%2Ftensorflow-android

**Comment by divzhere** [comment]
thanks Mark :')

**Comment by markmcd** [comment]
I've updated the link in the codelab & the update to the main tensorflow docs is on it's way out right now.

Thanks again
