### ISSUE TITLE
Step #4 Link to explore this graph

### ISSUE THREAD

**Issue by fgbarone** [googlecodelabs/tensorflow-style-transfer-android#9]
At step #4 theres a link to "Explore this graph interactively", which points to: https://googlecodelabs.github.io/tensorflow-style-transfer-android/

However, this URL is bugged and does not load the app as its supposed to... Inspector shows a missing file: /stylize_quantized.pbtxt

**Comment by markmcd** [comment]
Thanks for the report... I wonder how this deteriorated. Bizarre.

Anyways, it's fixed in 4baa0f18b0d04c4c682561fc1c462aae56eac617.

Thanks again!
